export interface QuestionData {
  topic: string;
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: string;
  explanation: string;
  difficulty: string;
  lessonSource: string;
}

export const questionsData: QuestionData[] = [
  // === DOMINANCE RELATIONSHIPS (Lesson 1 Module 3) ~18 questions ===
  {
    topic: "dominance",
    questionText: "In incomplete dominance, what is the phenotype of the F1 generation when a red-flowered four o'clock plant (RR) is crossed with a white-flowered one (rr)?",
    optionA: "All red flowers",
    optionB: "All pink flowers",
    optionC: "All white flowers",
    optionD: "A mix of red and white flowers",
    correctAnswer: "B",
    explanation: "In incomplete dominance, the F1 heterozygote (Rr) shows an intermediate phenotype. When RR (red) is crossed with rr (white), all F1 offspring are Rr with pink flowers — a blend of the two parental phenotypes.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "What is the phenotypic ratio in the F2 generation of a cross involving incomplete dominance (Rr × Rr)?",
    optionA: "3:1",
    optionB: "9:3:3:1",
    optionC: "1:2:1",
    optionD: "1:1:1:1",
    correctAnswer: "C",
    explanation: "In incomplete dominance, the F2 generation from Rr × Rr shows a 1:2:1 phenotypic ratio — 1 RR (red), 2 Rr (pink), and 1 rr (white). This matches the genotypic ratio because each genotype produces a distinct phenotype.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Overdominance occurs when the heterozygote (F1):",
    optionA: "Shows an intermediate phenotype between the two parents",
    optionB: "Exceeds the phenotypic measurements of both homozygous parents",
    optionC: "Shows both parental phenotypes simultaneously",
    optionD: "Is identical to one of the parents",
    correctAnswer: "B",
    explanation: "Overdominance (or heterosis) occurs when the heterozygote exceeds the phenotypic measurements of both homozygous parents. Example: Drosophila heterozygotes for fluorescent pigments have higher amounts than either parent.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "In co-dominance, what is observed in the heterozygote?",
    optionA: "An intermediate phenotype",
    optionB: "Only the dominant phenotype",
    optionC: "Both alleles expressed simultaneously",
    optionD: "No phenotype expressed",
    correctAnswer: "C",
    explanation: "In co-dominance, both alleles of a gene are fully expressed in the heterozygote. For example, in blood type MN, individuals with genotype MN express both M and N antigens on their red blood cells.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "A person with blood type AB has which antigens on their red blood cells?",
    optionA: "Only A antigen",
    optionB: "Only B antigen",
    optionC: "Both A and B antigens",
    optionD: "Neither A nor B antigens",
    correctAnswer: "C",
    explanation: "Blood type AB is a classic example of co-dominance. Individuals with genotype I^A I^B express both A and B antigens on their red blood cells. They have neither A nor B antibodies in their plasma.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Which blood type is known as the universal red cell donor?",
    optionA: "Type A",
    optionB: "Type B",
    optionC: "Type AB",
    optionD: "Type O",
    correctAnswer: "D",
    explanation: "Type O is the universal red cell donor because it has neither A nor B antigens on red cells, so it won't cause agglutination in any recipient. However, Type O has both A and B antibodies in the plasma.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Which blood type is the universal plasma donor?",
    optionA: "Type A",
    optionB: "Type B",
    optionC: "Type AB",
    optionD: "Type O",
    correctAnswer: "C",
    explanation: "Type AB is the universal plasma donor because individuals with AB blood have neither A nor B antibodies in their plasma, making their plasma safe to donate to any blood type.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Multiple alleles refer to:",
    optionA: "Two alleles for each gene pair",
    optionB: "More than two alleles existing in a gene system within a population",
    optionC: "Alleles on different chromosomes",
    optionD: "Dominant and recessive alleles only",
    correctAnswer: "B",
    explanation: "Multiple alleles exist when more than two alleles of a gene are found in a population. Although any individual diploid organism can only carry two alleles, the population as a whole may have many more (e.g., ABO blood group has I^A, I^B, and i alleles).",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "What is an antigen?",
    optionA: "A substance that destroys bacteria",
    optionB: "A marker (usually protein or sugar) that the immune system can recognize",
    optionC: "A type of white blood cell",
    optionD: "An enzyme that digests proteins",
    correctAnswer: "B",
    explanation: "An antigen is any marker — typically a protein or polysaccharide — on the surface of cells or viruses that the immune system recognizes. Each antigen has a unique shape that the immune system reads like a nametag.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Agglutination is:",
    optionA: "The process of cell division",
    optionB: "The visible expression of aggregation of antigens and antibodies",
    optionC: "The replication of DNA",
    optionD: "The synthesis of proteins",
    correctAnswer: "B",
    explanation: "Agglutination is the visible clumping that occurs when antigens and antibodies aggregate. It happens when antibodies bind to antigens on red blood cells, causing them to clump together.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Lethal genes that cause death only in the homozygous recessive condition are called:",
    optionA: "Dominant lethals",
    optionB: "Recessive lethals",
    optionC: "Semi-lethals",
    optionD: "Conditional lethals",
    correctAnswer: "B",
    explanation: "Recessive lethal genes cause death only when homozygous recessive. In the heterozygous state, there is no observable phenotypic effect. Example: heavy freckling caused by the gene for Xeroderma pigmentosum becomes lethal only when homozygous recessive.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Dominant lethal genes are characterized by:",
    optionA: "Death only in homozygous dominant individuals",
    optionB: "Death in heterozygous individuals",
    optionC: "No observable effect",
    optionD: "Death only in homozygous recessive individuals",
    correctAnswer: "B",
    explanation: "Dominant lethal genes cause death in heterozygous individuals. Example: the gene for epiloia in humans causes abnormal skin growths, severe mental defects, and multiple tumors leading to early death in heterozygotes.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Semi-lethal genes are those that:",
    optionA: "Cause immediate death",
    optionB: "Permit a larger proportion of affected genotypes to survive",
    optionC: "Have no effect on survival",
    optionD: "Only affect embryos",
    correctAnswer: "B",
    explanation: "Semi-lethals permit a larger proportion of affected genotypes to survive beyond the embryonic stage, compared to fully lethal genes which allow little or no survival among affected genotypes.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Modifier genes are genes that:",
    optionA: "Change the chromosome number",
    optionB: "Change phenotypic effects of other genes quantitatively through dilution or enhancement",
    optionC: "Replace missing genes",
    optionD: "Suppress all gene expression",
    correctAnswer: "B",
    explanation: "Modifier genes change the phenotypic effects of other genes in a quantitative fashion — either diluting or enhancing the effects of major genes. Suppressors are a type of modifier that completely suppress the phenotypic expression of a mutant gene.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Penetrance refers to:",
    optionA: "The degree to which a phenotype is expressed",
    optionB: "The proportion of genotypes that show an expected phenotype",
    optionC: "The number of genes in a cell",
    optionD: "The rate of mutation",
    correctAnswer: "B",
    explanation: "Penetrance is the proportion of individuals with a specific genotype that actually express the expected phenotype. Expressivity refers to the degree to which a particular phenotypic effect is expressed.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Sex-limited traits are those that:",
    optionA: "Only occur in one sex but are carried by both",
    optionB: "Appear in both sexes equally",
    optionC: "Are linked to the Y chromosome only",
    optionD: "Are caused by environmental factors",
    correctAnswer: "A",
    explanation: "Sex-limited traits are genetically present in both sexes but are physically expressed in only one sex. Examples include milk production in female cattle, horn development in male sheep, and beard growth in human males.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "An environmental mimic of gene action, where environmental influence is strong enough to copy a genetic trait, is called:",
    optionA: "Pleiotropy",
    optionB: "Penetrance",
    optionC: "Phenocopy",
    optionD: "Expressivity",
    correctAnswer: "C",
    explanation: "A phenocopy is an environmentally-caused mimic of a genetic trait. For example, diabetics dependent on insulin are phenocopies of normal individuals because the drug environment prevents expression of diabetes genes.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "Pleiotropy is a situation in which:",
    optionA: "Multiple genes affect one trait",
    optionB: "One gene has multiple phenotypic effects",
    optionC: "The environment affects gene expression",
    optionD: "Two alleles are equally expressed",
    correctAnswer: "B",
    explanation: "Pleiotropy occurs when one gene influences multiple, seemingly unrelated phenotypic traits. For example, a single gene mutation may affect multiple organ systems or produce a syndrome of symptoms.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  // === GENE CONCEPT / DNA STRUCTURE (Lesson 1 Module 4 Parts 1-2) ~15 questions ===
  {
    topic: "gene_expression",
    questionText: "What type of bond connects the phosphate group to the sugar in DNA?",
    optionA: "Hydrogen bond",
    optionB: "Peptide bond",
    optionC: "Phosphodiester bond",
    optionD: "Glycosidic bond",
    correctAnswer: "C",
    explanation: "The phosphodiester bond (also called phosphodiester linkage) connects the phosphate group to carbon 5 of one sugar and carbon 3 of the adjacent sugar, forming the sugar-phosphate backbone of DNA.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "In DNA, which nitrogen base pairs with Adenine (A)?",
    optionA: "Guanine (G)",
    optionB: "Cytosine (C)",
    optionC: "Thymine (T)",
    optionD: "Uracil (U)",
    correctAnswer: "C",
    explanation: "In DNA, Adenine (A) always pairs with Thymine (T) via two hydrogen bonds. Guanine (G) pairs with Cytosine (C) via three hydrogen bonds. Uracil (U) replaces Thymine in RNA.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "How many hydrogen bonds form between Guanine and Cytosine?",
    optionA: "One",
    optionB: "Two",
    optionC: "Three",
    optionD: "Four",
    correctAnswer: "C",
    explanation: "Guanine (G) pairs with Cytosine (C) via three hydrogen bonds, making this base pair stronger than the A-T pair which only has two hydrogen bonds. This contributes to DNA stability.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "The two strands of DNA are described as 'antiparallel' because:",
    optionA: "They run in the same direction",
    optionB: "They run in opposite directions (5' to 3' and 3' to 5')",
    optionC: "They are identical sequences",
    optionD: "They are perpendicular to each other",
    correctAnswer: "B",
    explanation: "DNA strands are antiparallel — one strand runs 5' to 3' while the complementary strand runs 3' to 5'. When one strand starts with 5', it ends with 3', and vice versa for the other strand.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "Who proposed the three-dimensional double helix structure of DNA in 1953?",
    optionA: "Rosalind Franklin",
    optionB: "James Watson and Francis Crick",
    optionC: "Gregor Mendel",
    optionD: "Thomas Hunt Morgan",
    correctAnswer: "B",
    explanation: "In 1953, James Watson and Francis Crick proposed the three-dimensional DNA double helix model, one of the most important discoveries in biology. Their work was based on X-ray diffraction data from Rosalind Franklin.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "In the DNA double helix, there are approximately how many base pairs in one complete 360° turn?",
    optionA: "5",
    optionB: "8",
    optionC: "10",
    optionD: "20",
    correctAnswer: "C",
    explanation: "The DNA double helix completes one full right-handed (clockwise) turn every 34 angstroms, and there are approximately 10 base pairs in one complete 360° turn. Each base pair occupies about 3.4 angstroms.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "Which factor does NOT contribute to DNA stability?",
    optionA: "Covalent bonds in the sugar-phosphate backbone",
    optionB: "Hydrogen bonds between bases",
    optionC: "Hydrophobic interactions between stacked nitrogen bases",
    optionD: "Ionic bonds with water molecules",
    correctAnswer: "D",
    explanation: "DNA stability comes from: (1) covalent phosphodiester bonds in the backbone, (2) hydrogen bonds between paired bases, and (3) hydrophobic interactions between stacked nitrogen bases. Ionic bonds with water do not contribute to stability.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "RNA differs from DNA in that RNA:",
    optionA: "Is double-stranded",
    optionB: "Contains thymine instead of uracil",
    optionC: "Is single-stranded and contains ribose sugar",
    optionD: "Has deoxyribose sugar",
    correctAnswer: "C",
    explanation: "RNA is single-stranded (unlike double-stranded DNA), contains ribose sugar (instead of deoxyribose), and uses Uracil (U) instead of Thymine (T). Its backbone is composed of alternating ribose sugar and phosphate groups.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 4 Part 2"
  },
  {
    topic: "gene_expression",
    questionText: "Which type of RNA carries amino acids to the site of protein synthesis?",
    optionA: "mRNA",
    optionB: "tRNA",
    optionC: "rRNA",
    optionD: "snRNA",
    correctAnswer: "B",
    explanation: "Transfer RNA (tRNA) carries amino acids from different locations in the cytoplasm to the precise site of protein synthesis (the ribosome). It has a cloverleaf configuration with an amino-acyl arm and an anticodon arm.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 4 Part 2"
  },
  {
    topic: "gene_expression",
    questionText: "Which type of RNA provides the template for amino acid sequence during protein synthesis?",
    optionA: "mRNA",
    optionB: "tRNA",
    optionC: "rRNA",
    optionD: "miRNA",
    correctAnswer: "A",
    explanation: "Messenger RNA (mRNA) transfers information from DNA to the ribosome and provides the template that codes for the amino acid sequence of proteins. Every three nucleotides (a codon) specifies one amino acid.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 4 Part 2"
  },
  {
    topic: "gene_expression",
    questionText: "Ribosomal RNA (rRNA) functions to:",
    optionA: "Carry amino acids to the ribosome",
    optionB: "Direct the catalysis of protein synthesis as part of ribosomes",
    optionC: "Transfer genetic information from nucleus to cytoplasm",
    optionD: "Regulate gene expression",
    correctAnswer: "B",
    explanation: "rRNA is complexed with proteins to form ribosomes and directs the catalysis of protein synthesis. Ribosomes are sometimes referred to as ribozymes because of their catalytic activity.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 4 Part 2"
  },
  {
    topic: "gene_expression",
    questionText: "The Human Immunodeficiency Virus (HIV/AIDS virus) uses which type of genetic material?",
    optionA: "DNA only",
    optionB: "RNA",
    optionC: "Both DNA and RNA",
    optionD: "Proteins",
    correctAnswer: "B",
    explanation: "Many viruses, including HIV (the AIDS virus) and tomato mosaic virus, carry RNA as their genetic material rather than DNA. Some viruses use DNA, but RNA viruses are common.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 4 Part 2"
  },
  // === DNA REPLICATION (Lesson 2 Module 4 Part 1) ~18 questions ===
  {
    topic: "dna_replication",
    questionText: "DNA replication is described as 'semi-conservative' because:",
    optionA: "Both new strands are completely new",
    optionB: "Both old strands are conserved",
    optionC: "Each new DNA molecule contains one old strand and one new strand",
    optionD: "Only half of the DNA is replicated",
    correctAnswer: "C",
    explanation: "In semi-conservative replication, each new DNA molecule contains one old (parental) strand and one newly synthesized strand. The two parental strands separate and each serves as a template for a new complementary strand.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "Which enzyme unwinds the DNA double helix by breaking hydrogen bonds between nitrogen bases?",
    optionA: "DNA polymerase",
    optionB: "Helicase (Helix Unwinding Protein)",
    optionC: "Ligase",
    optionD: "RNA primase",
    correctAnswer: "B",
    explanation: "Helicase (also called Helix Unwinding Protein or HUP) uses ATP to unwind the DNA by breaking hydrogen bonds between nitrogen bases, separating the two strands to serve as templates.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "What is the function of DNA gyrase during replication?",
    optionA: "To synthesize new DNA strands",
    optionB: "To relax twisting tension (supercoils) created during unwinding",
    optionC: "To remove RNA primers",
    optionD: "To join Okazaki fragments",
    correctAnswer: "B",
    explanation: "DNA gyrase relaxes the twisting tension (supercoils) that builds up ahead of the replication fork as the DNA unwinds. Without gyrase, the DNA would become too twisted for replication to continue.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "What is the role of RNA primers in DNA replication?",
    optionA: "They provide the energy for DNA synthesis",
    optionB: "They provide the 3'-OH group needed by DNA polymerase to start elongation",
    optionC: "They proofread the newly synthesized DNA",
    optionD: "They seal gaps between DNA fragments",
    correctAnswer: "B",
    explanation: "RNA primers provide the free 3'-OH group that DNA polymerase III needs to begin adding nucleotides. DNA polymerase cannot initiate synthesis de novo — it can only extend from an existing 3'-OH end.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "On which strand of DNA are multiple RNA primers needed?",
    optionA: "Leading strand",
    optionB: "Lagging strand",
    optionC: "Both strands equally",
    optionD: "Neither strand",
    correctAnswer: "B",
    explanation: "Multiple RNA primers are needed on the lagging strand because it is synthesized discontinuously in the 5' to 3' direction away from the replication fork. Each Okazaki fragment requires its own primer. The leading strand needs only one primer because it is synthesized continuously.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "Which enzyme is responsible for removing RNA primers and replacing them with DNA nucleotides?",
    optionA: "DNA polymerase III",
    optionB: "DNA polymerase I",
    optionC: "Helicase",
    optionD: "Ligase",
    correctAnswer: "B",
    explanation: "DNA polymerase I has exonuclease activity that removes RNA primers by digesting them from 3' to 5'. It then replaces the excised primers with DNA nucleotides, though it leaves a small break between DNA segments.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "Okazaki fragments are:",
    optionA: "RNA primers on the leading strand",
    optionB: "Short DNA segments (1,000-2,000 nucleotides) synthesized on the lagging strand",
    optionC: "Enzymes that seal DNA breaks",
    optionD: "Proteins that bind to single-stranded DNA",
    correctAnswer: "B",
    explanation: "Okazaki fragments are short DNA segments (about 1,000-2,000 nucleotides long) synthesized on the lagging strand. They are separated by RNA primers and are later joined together by DNA ligase.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "Which enzyme seals the gaps or breaks between newly synthesized DNA strands?",
    optionA: "DNA polymerase III",
    optionB: "DNA polymerase I",
    optionC: "DNA ligase",
    optionD: "Helicase",
    correctAnswer: "C",
    explanation: "DNA ligase seals the gaps or breaks (nicks) between Okazaki fragments on the lagging strand by forming phosphodiester bonds, completing the replication process and producing two intact daughter DNA molecules.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "The leading strand elongates in which direction relative to the unwinding of DNA?",
    optionA: "Away from the unwinding region",
    optionB: "Toward the unwinding region",
    optionC: "Perpendicular to the unwinding region",
    optionD: "In both directions",
    correctAnswer: "B",
    explanation: "The leading strand elongates continuously toward the unwinding region (replication fork) in the 5' to 3' direction. Its synthesis follows the movement of the helicase as it unwinds the parental DNA.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "The Central Dogma of Molecular Biology consists of which three processes?",
    optionA: "Replication, Transcription, Translation",
    optionB: "Mitosis, Meiosis, Fertilization",
    optionC: "Mutation, Selection, Adaptation",
    optionD: "Transcription, Reverse transcription, Translation",
    correctAnswer: "A",
    explanation: "The Central Dogma describes the flow of genetic information: Replication (DNA → DNA), Transcription (DNA → RNA), and Translation (RNA → Protein). This applies to all organisms except some RNA viruses that undergo reverse transcription.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "How many essential amino acids cannot be synthesized by the human body?",
    optionA: "5",
    optionB: "9",
    optionC: "11",
    optionD: "20",
    correctAnswer: "B",
    explanation: "Out of 20 amino acids, 9 are essential — meaning they cannot be synthesized by the body and must be obtained through food. These are: isoleucine, histidine, lysine, leucine, phenylalanine, tryptophan, methionine, threonine, and valine.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "Which essential amino acid is involved in the production of serotonin, which regulates sleep and mood?",
    optionA: "Methionine",
    optionB: "Leucine",
    optionC: "Tryptophan",
    optionD: "Valine",
    correctAnswer: "C",
    explanation: "Tryptophan is involved in the production of vitamin B3 and serotonin hormones. Serotonin plays a vital role in maintaining appetite, regulating sleep, and boosting moods.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  // === TRANSCRIPTION (Lesson 2 Module 4 Part 2) ~15 questions ===
  {
    topic: "transcription",
    questionText: "During transcription, which nitrogen base in RNA complements Adenine (A) in the DNA template?",
    optionA: "Thymine (T)",
    optionB: "Uracil (U)",
    optionC: "Cytosine (C)",
    optionD: "Guanine (G)",
    correctAnswer: "B",
    explanation: "During transcription, RNA polymerase complements A with Uracil (U) rather than Thymine (T). This is a key difference between DNA and RNA — RNA contains U instead of T.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "What is the function of the sigma factor in transcription initiation?",
    optionA: "It synthesizes RNA",
    optionB: "It recognizes the promoter sequence so RNA polymerase can bind selectively",
    optionC: "It terminates transcription",
    optionD: "It splices introns",
    correctAnswer: "B",
    explanation: "The sigma factor recognizes the promoter sequence on DNA, enabling RNA polymerase to selectively bind to the correct starting point for transcription. Once bound, sigma dissociates and is free for another round.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "Which strand of DNA does RNA polymerase use as a template during transcription?",
    optionA: "The coding strand",
    optionB: "The anticoding (template) strand",
    optionC: "Both strands simultaneously",
    optionD: "Neither strand",
    correctAnswer: "B",
    explanation: "RNA polymerase moves along the anticoding (template) strand of DNA, separating the two strands and synthesizing a complementary RNA molecule. The coding strand has the same sequence as the RNA (except T→U).",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "In which direction is RNA synthesized during transcription?",
    optionA: "3' to 5'",
    optionB: "5' to 3'",
    optionC: "Both directions",
    optionD: "Random direction",
    correctAnswer: "B",
    explanation: "RNA synthesis always occurs in the 5' to 3' direction, following Watson-Crick base pairing rules. Ribonucleotides are added to the growing 3' end of the RNA chain.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "What happens to the DNA strands after a segment has been transcribed?",
    optionA: "They remain separated",
    optionB: "They reanneal (re-pair) because DNA-DNA interaction is stronger than DNA-RNA",
    optionC: "They are degraded",
    optionD: "They form a permanent RNA-DNA hybrid",
    correctAnswer: "B",
    explanation: "As soon as a segment is transcribed, the DNA strands reanneal (re-pair) because the DNA-DNA interaction is stronger than the DNA-RNA interaction. This ensures that only a single-stranded RNA is produced.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "Every three nucleotides of mRNA that code for one specific amino acid is called a:",
    optionA: "Anticodon",
    optionB: "Codon",
    optionC: "Intron",
    optionD: "Exon",
    correctAnswer: "B",
    explanation: "A codon is a sequence of three nucleotides in mRNA that specifies a particular amino acid. The genetic code chart maps each codon to its corresponding amino acid. There are 64 possible codons.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "tRNA anticodons complement the codons on:",
    optionA: "DNA",
    optionB: "rRNA",
    optionC: "mRNA",
    optionD: "Other tRNA molecules",
    correctAnswer: "C",
    explanation: "tRNA contains anticodons — three nucleotides that are complementary to the codons on mRNA. This complementarity ensures the correct amino acid is delivered to the ribosome according to the mRNA sequence.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "The cloverleaf configuration is characteristic of:",
    optionA: "mRNA",
    optionB: "rRNA",
    optionC: "tRNA",
    optionD: "DNA",
    correctAnswer: "C",
    explanation: "tRNA assumes a cloverleaf configuration with an amino-acyl arm (carrying the amino acid) and an anticodon arm (containing the three nucleotides that complement the mRNA codon). There are 20 different tRNAs, each carrying a different amino acid.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "Ribosomes consist of which subunits?",
    optionA: "20S and 30S",
    optionB: "30S and 50S",
    optionC: "40S and 60S",
    optionD: "50S and 70S",
    correctAnswer: "B",
    explanation: "Ribosomes consist of a small (30S) and a large (50S) subunit. When joined, they form a 70S complex. Eukaryotic ribosomes are larger (40S + 60S = 80S), but prokaryotic ribosomes are 30S + 50S = 70S.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "In the ribosome, the P-site (peptidyl-binding site) is where:",
    optionA: "New aminoacyl-tRNA enters",
    optionB: "The growing polypeptide chain is held",
    optionC: "mRNA exits",
    optionD: "Ribosome subunits separate",
    correctAnswer: "B",
    explanation: "The P-site (peptidyl-binding or donor site) holds the tRNA carrying the growing polypeptide chain. The A-site (amino-acyl or acceptor site) is where new aminoacyl-tRNA molecules enter.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "Which enzyme adds the 5' cap to pre-mRNA during RNA processing?",
    optionA: "RNA polymerase",
    optionB: "DNA ligase",
    optionC: "Guanylyl transferase (capping enzyme)",
    optionD: "Spliceosome",
    correctAnswer: "C",
    explanation: "The 5' cap (a modified guanine, 7-methyl G) is added to the 5' end of pre-mRNA by a capping enzyme. This cap protects the RNA from degradation and helps in ribosome binding during translation.",
    difficulty: "hard",
    lessonSource: "Gene Expression"
  },
  // === TRANSLATION (Lesson 2 Module 4 Part 3) ~15 questions ===
  {
    topic: "translation",
    questionText: "The first amino acid attached to the initiating tRNA during translation is:",
    optionA: "Regular methionine",
    optionB: "Formylated methionine (fmet)",
    optionC: "Glycine",
    optionD: "Phenylalanine",
    correctAnswer: "B",
    explanation: "In prokaryotes, translation initiation uses formylated methionine (fmet) as the first amino acid. The formyl group prevents elongation at the amino end. The initiator tRNA complements the AUG codon at the 5' end of mRNA.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "What is the role of initiation factors (IF1, IF2, IF3) in translation?",
    optionA: "They synthesize amino acids",
    optionB: "IF3 binds mRNA to 30S subunit, IF1 prevents premature binding, IF2 brings fmet-tRNA",
    optionC: "They terminate translation",
    optionD: "They splice introns",
    correctAnswer: "B",
    explanation: "Initiation factors orchestrate the assembly of the translation machinery: IF3 binds mRNA to the 30S subunit, IF1 prevents premature tRNA binding, and IF2 brings the initiator fmet-tRNA to the P-site and completes the 70S ribosome by binding the 50S subunit.",
    difficulty: "hard",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "During elongation, which enzyme catalyzes the peptide bond between amino acids?",
    optionA: "DNA polymerase",
    optionB: "RNA polymerase",
    optionC: "Peptidyl transferase",
    optionD: "Helicase",
    correctAnswer: "C",
    explanation: "Peptidyl transferase, located in the 50S ribosomal subunit, catalyzes the formation of a peptide bond between the amino acid at the P-site and the incoming amino acid at the A-site.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "After peptide bond formation, what happens to the tRNA at the P-site?",
    optionA: "It remains at the P-site",
    optionB: "It is released to the cytoplasm for reactivation",
    optionC: "It is degraded",
    optionD: "It moves to the A-site",
    correctAnswer: "B",
    explanation: "After the peptide bond forms, the empty tRNA at the P-site is released into the cytoplasm where it can be recharged with another amino acid. The ribosome then translocates, moving the peptidyl-tRNA from the A-site to the P-site.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "Which of the following is a stop codon that signals termination of translation?",
    optionA: "AUG",
    optionB: "UAA",
    optionC: "GGC",
    optionD: "CUA",
    correctAnswer: "B",
    explanation: "UAA is one of three stop codons (along with UAG and UGA) that signal termination of translation. When the ribosome encounters a stop codon in the A-site, release factors (RF1 or RF2) cause the polypeptide to be released. AUG is the start codon.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "What happens when a stop codon is encountered during translation?",
    optionA: "Another amino acid is added",
    optionB: "Release factors dissociate the polypeptide and tRNA from the ribosome",
    optionC: "The ribosome continues translating",
    optionD: "The mRNA is degraded",
    correctAnswer: "B",
    explanation: "When a stop codon (UAA, UAG, or UGA) enters the A-site, release factors (RF1 or RF2) bind, causing the polypeptide chain to be released from the tRNA and the ribosomal subunits to dissociate. The polypeptide may then undergo further processing to become a functional protein.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "Albinism is caused by a block in the conversion of:",
    optionA: "Phenylalanine to Tyrosine",
    optionB: "Tyrosine to Melanin",
    optionC: "Glucose to Glycogen",
    optionD: "Cholesterol to Vitamin D",
    correctAnswer: "B",
    explanation: "Albinism results from a block in the conversion of Tyrosine to Melanin. Melanin is the functional protein that acts as pigment in the skin. Phenylalanine is first converted to Tyrosine, which is then converted to Melanin.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "Phenylketonuria (PKU) is characterized by:",
    optionA: "Absence of melanin",
    optionB: "Too much phenylalanine in the body causing musty odor and neurological problems",
    optionC: "Excessive melanin production",
    optionD: "Lack of insulin",
    correctAnswer: "B",
    explanation: "Phenylketonuria is caused by a block in phenylalanine metabolism. Excess phenylalanine accumulates, causing a musty odor in breath, skin, or urine, and neurological problems including seizures. It results from inability to convert phenylalanine to tyrosine.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "The A-site in the ribosome is also known as the:",
    optionA: "Peptidyl-binding site",
    optionB: "Amino-acyl or acceptor site",
    optionC: "Exit site",
    optionD: "Start site",
    correctAnswer: "B",
    explanation: "The A-site is the amino-acyl site (or acceptor site) where new aminoacyl-tRNA molecules enter the ribosome. The P-site is the peptidyl-binding site where the growing polypeptide chain is held.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "Translocation during translation refers to:",
    optionA: "Movement of mRNA from nucleus to cytoplasm",
    optionB: "Movement of the ribosome along mRNA, shifting tRNA from A-site to P-site",
    optionC: "Transport of amino acids to the ribosome",
    optionD: "Splicing of introns from pre-mRNA",
    correctAnswer: "B",
    explanation: "Translocation is the movement of the ribosome along the mRNA after peptide bond formation. This shifts the peptidyl-tRNA from the A-site to the P-site, leaving the A-site free for the next incoming aminoacyl-tRNA.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  // === LINKAGE & SEX DETERMINATION (Lesson 2 Module 3) ~18 questions ===
  {
    topic: "linkage",
    questionText: "Linkage refers to:",
    optionA: "The independent assortment of genes",
    optionB: "The physical arrangement of genes on the same chromosome causing them to be inherited together",
    optionC: "The exchange of genetic material between non-homologous chromosomes",
    optionD: "The random distribution of chromosomes during meiosis",
    correctAnswer: "B",
    explanation: "Linkage is the physical arrangement of genes on the same chromosome, causing them to be inherited together by succeeding generations. The closer genes are to each other, the greater the possibility they will be inherited together.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Who coined the term 'linkage' through studies on Drosophila chromosomes?",
    optionA: "Gregor Mendel",
    optionB: "Thomas Hunt Morgan",
    optionC: "James Watson",
    optionD: "Francis Crick",
    correctAnswer: "B",
    explanation: "Thomas Hunt Morgan coined the term 'linkage' through his studies on Drosophila melanogaster chromosomes. He discovered that genes located on the same chromosome tend to be inherited together.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "The number of linkage groups in an organism equals its:",
    optionA: "Diploid chromosome number",
    optionB: "Haploid chromosome number",
    optionC: "Number of genes",
    optionD: "Number of autosomes",
    correctAnswer: "B",
    explanation: "The number of linkage groups equals the haploid chromosome number. For example, humans have 23 linkage groups corresponding to 23 pairs of chromosomes (22 autosomes + X and Y sex chromosomes). Drosophila has 4 linkage groups.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "In a testcross of independently assorting genes (EeFf × eeff), the expected phenotypic ratio is:",
    optionA: "1:1:1:1",
    optionB: "3:1",
    optionC: "9:3:3:1",
    optionD: "1:2:1",
    correctAnswer: "A",
    explanation: "For independently assorting genes in a testcross (EeFf × eeff), the expected phenotypic ratio is 1:1:1:1 (EeFf, eeff, Eeff, eeFf). Two classes are parental types and two are recombinant types, with 50% recombinant frequency.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Complete linkage occurs when:",
    optionA: "Genes are far apart on the same chromosome",
    optionB: "Non-allelic genes are closely located on the same chromosome and do not assort independently",
    optionC: "Genes are on different chromosomes",
    optionD: "Crossing over occurs frequently",
    correctAnswer: "B",
    explanation: "Complete linkage occurs when two or more non-allelic genes are closely located on the same chromosome in linear order. They do not assort independently, and testcross progenies show only parental types.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Incomplete linkage is characterized by:",
    optionA: "Zero recombination frequency",
    optionB: "Recombination frequency of less than 50%",
    optionC: "Recombination frequency of exactly 50%",
    optionD: "Genes on different chromosomes",
    correctAnswer: "B",
    explanation: "Incomplete linkage occurs when genes are on the same chromosome but far apart, allowing crossing over between them. The recombination frequency is less than 50% but greater than 0%. Four progeny genotypes are observed in a testcross.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "In Drosophila, crossing-over is completely suppressed in:",
    optionA: "Females",
    optionB: "Males",
    optionC: "Both sexes equally",
    optionD: "Larvae only",
    correctAnswer: "B",
    explanation: "In Drosophila melanogaster, crossing-over is completely suppressed in males (the heterogametic sex). This means no recombination occurs in male Drosophila, so all offspring show parental combinations only.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Which factor does NOT affect recombination frequency?",
    optionA: "Sex of the organism",
    optionB: "Maternal age",
    optionC: "Temperature",
    optionD: "Gravity",
    correctAnswer: "D",
    explanation: "Factors affecting recombination frequency include: sex (heterogametic sex has lower crossover frequency), maternal age (increased age decreases crossing over), temperature (cooler or warmer than 22°C increases rate in Drosophila), and cytoplasmic effects. Gravity does not affect recombination.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "In the XX-XY mechanism of sex determination, females are:",
    optionA: "XY",
    optionB: "XX",
    optionC: "XO",
    optionD: "YY",
    correctAnswer: "B",
    explanation: "In the XX-XY system (found in most mammals, humans, and insects), females have two X chromosomes (XX) and are homogametic, while males have one X and one Y chromosome (XY) and are heterogametic.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "In birds, moths, and butterflies, which sex is heterogametic?",
    optionA: "Male (XY)",
    optionB: "Female (XY or ZW)",
    optionC: "Both sexes",
    optionD: "Neither sex",
    correctAnswer: "B",
    explanation: "In birds, moths, and butterflies, the sex determination system is reversed — females are the heterogametic sex (ZW) while males are homogametic (ZZ). This is the opposite of the mammalian XX-XY system.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Haplo-diploidy in bees and ants means that:",
    optionA: "All individuals are diploid",
    optionB: "Males develop from unfertilized eggs and are haploid; females develop from fertilized eggs and are diploid",
    optionC: "All individuals are haploid",
    optionD: "Both males and females are diploid",
    correctAnswer: "B",
    explanation: "In haplo-diploidy (found in bees and ants), males develop from unfertilized eggs and are haploid (no fathers, only grandfathers from the maternal side). Females develop from fertilized eggs and are diploid. Some females become queens while others become sterile workers.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Hemophilia in humans is an example of:",
    optionA: "Autosomal dominant inheritance",
    optionB: "X-linked recessive inheritance",
    optionC: "Y-linked inheritance",
    optionD: "Mitochondrial inheritance",
    correctAnswer: "B",
    explanation: "Hemophilia is an X-linked recessive disorder. The gene is located on the X chromosome. A woman can be a carrier (heterozygous) without showing symptoms, but can transmit the condition to half of her sons.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "In the marine worm Bonellia, sex determination is:",
    optionA: "Genetic only",
    optionB: "Environmental — larvae that attach to mature females become males due to masculinizing hormones",
    optionC: "Temperature-dependent",
    optionD: "Random",
    correctAnswer: "B",
    explanation: "In Bonellia, environmental sex determination occurs: larvae that remain free-swimming become females, while larvae that attach to mature females become males due to masculinizing hormones secreted by the females.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "The coral reef fish Labroides dimidiatus demonstrates:",
    optionA: "Genetic sex determination",
    optionB: "Complete sex reversal when the male dies",
    optionC: "Haplo-diploidy",
    optionD: "Temperature-dependent sex determination",
    correctAnswer: "B",
    explanation: "Labroides dimidiatus lives in groups with one male and several females. When the male dies, the dominant female repels new males, starts courting behavior, and undergoes complete sex reversal to become a functional male within about two weeks.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Porcupine man (ichthyosis hystrix) is an example of:",
    optionA: "X-linked inheritance",
    optionB: "Y-linked inheritance affecting only males",
    optionC: "Autosomal recessive",
    optionD: "Mitochondrial inheritance",
    correctAnswer: "B",
    explanation: "Porcupine man is a Y-linked trait transmitted from father to son. Only males are affected because the Y chromosome carries few genes and is only present in males. Other Y-linked traits include webbed toes and hypertrichosis of the ears.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 3"
  },
  // === MUTATIONS (Lesson 1 Module 5 + mutation-1) ~20 questions ===
  {
    topic: "mutation",
    questionText: "A mutation is defined as:",
    optionA: "A temporary change in the phenotype",
    optionB: "A sudden heritable change in the genotype of an individual",
    optionC: "A change in the environment",
    optionD: "A normal cellular process",
    correctAnswer: "B",
    explanation: "A mutation is a sudden heritable change in the genotype of an individual. These changes are essentially permanent, can occur naturally or be induced by mutagens, and result in distinct genetic effects.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "Euploidy refers to:",
    optionA: "Changes involving individual chromosomes",
    optionB: "Changes involving whole sets of chromosomes",
    optionC: "Changes in DNA base pairs only",
    optionD: "Changes in protein structure",
    correctAnswer: "B",
    explanation: "Euploidy refers to changes involving whole genome sets or entire sets of chromosomes. It includes monoploidy (one set) and polyploidy (three or more sets). Aneuploidy, by contrast, involves individual chromosomes.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "Autopolyploidy is characterized by:",
    optionA: "Genomes from different species",
    optionB: "Multiplication of one basic genome",
    optionC: "Loss of individual chromosomes",
    optionD: "Gain of individual chromosomes",
    correctAnswer: "B",
    explanation: "Autopolyploidy is the multiplication of one basic genome. Example: the Cavendish banana variety is an autotriploid (3n) with AAA set chromosomes — all three sets are identical.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "Allopolyploidy differs from autopolyploidy in that:",
    optionA: "It involves fewer chromosomes",
    optionB: "The multiple genome sets are not identical (from different species)",
    optionC: "It only occurs in animals",
    optionD: "It results in sterile offspring",
    correctAnswer: "B",
    explanation: "In allopolyploidy, the genomes making up the multiple sets are not identical — they come from different species. Example: tobacco with ABCD set of chromosomes is an allotetraploid (4n).",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "Turner syndrome is characterized by:",
    optionA: "An extra X chromosome (47, XXX)",
    optionB: "A diploid number of 45 (XO) with sexual infantilism and underdeveloped reproductive organs",
    optionC: "An extra Y chromosome (47, XYY)",
    optionD: "Trisomy 21",
    correctAnswer: "B",
    explanation: "Turner syndrome (45, XO) is the only monosomy compatible with life. Individuals have a diploid chromosome number of 45 with sexual infantilism, underdeveloped reproductive organs, short stature, and possible mental retardation.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "Klinefelter syndrome (47, XXY) is characterized by:",
    optionA: "Normal male development",
    optionB: "Male underdevelopment, sterility, and possible mental retardation",
    optionC: "Female with extra X chromosome",
    optionD: "Short stature and webbed neck",
    correctAnswer: "B",
    explanation: "Klinefelter syndrome (47, XXY) results in male underdevelopment, sterility, and possible mental retardation. It is a sex chromosome aneuploidy where males have an extra X chromosome.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "Down syndrome is caused by:",
    optionA: "Monosomy of chromosome 21",
    optionB: "Trisomy of chromosome 21 (47 chromosomes)",
    optionC: "Deletion of chromosome 21",
    optionD: "Translocation involving chromosome 21",
    correctAnswer: "B",
    explanation: "Down syndrome is caused by trisomy 21 — an extra copy of chromosome 21, giving a total of 47 chromosomes. It results in mental retardation, slanting eyes (mongolism), saddle nose, and a swollen tongue.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "A deficiency or deletion in a chromosome refers to:",
    optionA: "Addition of a chromosome segment",
    optionB: "Loss of a segment of the chromosome",
    optionC: "Rotation of a chromosome segment 180 degrees",
    optionD: "Exchange between non-homologous chromosomes",
    correctAnswer: "B",
    explanation: "A deficiency (deletion) is the loss of a segment of a chromosome. Genetic effects include lethality, pseudo-dominance, no crossing-over in the deleted region, and unique phenotypes.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "An inversion in a chromosome involves:",
    optionA: "Loss of a segment",
    optionB: "Rotation of a chromosome segment to a full 180 degrees",
    optionC: "Duplication of a segment",
    optionD: "Exchange between two chromosomes",
    correctAnswer: "B",
    explanation: "An inversion is the rotation of a chromosome segment to a full 180 degrees. It produces a new linkage order and can result in partial or complete sterility due to problems during meiosis.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "A reciprocal translocation occurs when:",
    optionA: "A segment is duplicated",
    optionB: "Single breaks in two non-homologous chromosomes produce an exchange of sections",
    optionC: "A segment is inverted",
    optionD: "A chromosome is lost",
    correctAnswer: "B",
    explanation: "A reciprocal translocation (interchange) occurs when single breaks in two non-homologous chromosomes produce an exchange of chromosome sections between them. It often causes sterility.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "A base pair substitution is a type of:",
    optionA: "Chromosomal mutation",
    optionB: "Gene mutation",
    optionC: "Genome mutation",
    optionD: "Epigenetic change",
    correctAnswer: "B",
    explanation: "Base pair substitution is a gene mutation — a change at the DNA level where one base pair is replaced by another. For example, an A-T pair might be substituted with a G-C pair.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "A frameshift mutation is caused by:",
    optionA: "Substitution of one base pair",
    optionB: "Addition or deletion of a single nucleotide or a few nucleotides not divisible by three",
    optionC: "Exchange of chromosome segments",
    optionD: "Duplication of a gene",
    correctAnswer: "B",
    explanation: "Frameshift mutations are caused by insertion or deletion of a number of nucleotides not evenly divisible by three. This disrupts the reading frame (codon grouping), resulting in a completely different translation from the original.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "Transposons (jumping genes) are:",
    optionA: "Genes that duplicate DNA",
    optionB: "Movable genetic elements that can change position in the genome",
    optionC: "Enzymes that repair DNA",
    optionD: "Proteins that bind to DNA",
    correctAnswer: "B",
    explanation: "Transposons (or jumping genes) are movable genetic elements that can change their position within the genome. They were discovered by Barbara McClintock and can cause mutations when they insert into new locations.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "Which of the following is an example of a physical mutagen?",
    optionA: "Nitrous acid",
    optionB: "Colchicine",
    optionC: "X-rays",
    optionD: "Chloral hydrate",
    correctAnswer: "C",
    explanation: "X-rays are a form of ionizing radiation — a physical mutagen. Ionizing radiation (including X-rays, gamma rays, protons, neutrons, alpha and beta particles) breaks DNA strands and can kill viruses. Chemical mutagens include nitrous acid and colchicine.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "mutation",
    questionText: "A transition mutation is the replacement of:",
    optionA: "A purine with a pyrimidine or vice versa",
    optionB: "A purine with another purine, or a pyrimidine with another pyrimidine",
    optionC: "Any base with any other base",
    optionD: "A codon with a stop codon",
    correctAnswer: "B",
    explanation: "A transition is a point mutation where a purine is replaced by another purine (A ↔ G) or a pyrimidine is replaced by another pyrimidine (C ↔ T). A transversion is a purine-to-pyrimidine or pyrimidine-to-purine change.",
    difficulty: "medium",
    lessonSource: "mutation-1"
  },
  {
    topic: "mutation",
    questionText: "Sickle cell disease is caused by which type of mutation?",
    optionA: "Frameshift mutation",
    optionB: "Missense mutation — replacement of A by T at the 17th nucleotide changes GAG (Glu) to GTG (Val)",
    optionC: "Nonsense mutation",
    optionD: "Silent mutation",
    correctAnswer: "B",
    explanation: "Sickle cell disease is a missense mutation. The replacement of A by T at the 17th nucleotide of the beta-globin gene changes the codon GAG (glutamic acid) to GTG (valine), altering the 6th amino acid in the hemoglobin chain.",
    difficulty: "hard",
    lessonSource: "mutation-1"
  },
  {
    topic: "mutation",
    questionText: "A nonsense mutation results in:",
    optionA: "A different amino acid being inserted",
    optionB: "A premature stop codon that truncates the protein",
    optionC: "No change in the amino acid sequence",
    optionD: "An extended protein",
    correctAnswer: "B",
    explanation: "A nonsense mutation changes a sense codon to a stop codon (UAA, UAG, or UGA), causing premature termination of translation. This produces a truncated, usually nonfunctional protein. Examples include thalassemia and Duchenne muscular dystrophy.",
    difficulty: "medium",
    lessonSource: "mutation-1"
  },
  {
    topic: "mutation",
    questionText: "A silent mutation occurs when:",
    optionA: "The codon changes but codes for the same amino acid",
    optionB: "No protein is produced",
    optionC: "A stop codon is created",
    optionD: "The reading frame is shifted",
    correctAnswer: "A",
    explanation: "A silent mutation is a change in the DNA sequence that does not alter the amino acid sequence of the protein. This occurs due to the degeneracy (redundancy) of the genetic code — multiple codons can specify the same amino acid.",
    difficulty: "easy",
    lessonSource: "mutation-1"
  },
  {
    topic: "mutation",
    questionText: "Tautomerism causes mutations by:",
    optionA: "Breaking DNA strands",
    optionB: "Repositioning a hydrogen atom, changing base pairing properties",
    optionC: "Removing entire bases",
    optionD: "Duplicating chromosomes",
    correctAnswer: "B",
    explanation: "Tautomerism is a spontaneous molecular-level mutation where a hydrogen atom repositioning changes a base's pairing properties. For example, a rare tautomer of cytosine might pair with adenine instead of guanine, causing a mispairing during replication.",
    difficulty: "hard",
    lessonSource: "mutation-1"
  },
  // === GENE EXPRESSION OVERVIEW ~12 questions ===
  {
    topic: "gene_expression",
    questionText: "According to the Central Dogma, information flows from:",
    optionA: "Protein → RNA → DNA",
    optionB: "DNA → RNA → Protein",
    optionC: "RNA → DNA → Protein",
    optionD: "Protein → DNA → RNA",
    correctAnswer: "B",
    explanation: "The Central Dogma states that genetic information flows from DNA to RNA to Protein. DNA replication copies DNA, transcription converts DNA to RNA, and translation converts RNA to protein. Reverse transcription (RNA → DNA) occurs only in some retroviruses.",
    difficulty: "easy",
    lessonSource: "Gene Expression"
  },
  {
    topic: "gene_expression",
    questionText: "Helicase is required during DNA replication to:",
    optionA: "Synthesize new DNA strands",
    optionB: "Unwind the DNA double helix by breaking hydrogen bonds",
    optionC: "Seal Okazaki fragments",
    optionD: "Add RNA primers",
    correctAnswer: "B",
    explanation: "Helicase (also called Helix Unwinding Protein) unwinds the DNA double helix by breaking the hydrogen bonds between complementary nitrogen bases, creating single-stranded templates for replication.",
    difficulty: "easy",
    lessonSource: "Gene Expression"
  },
  {
    topic: "gene_expression",
    questionText: "Single-Stranded Binding Proteins (SSBPs) function to:",
    optionA: "Synthesize DNA",
    optionB: "Keep the separated DNA strands from reannealing",
    optionC: "Remove RNA primers",
    optionD: "Join DNA fragments",
    correctAnswer: "B",
    explanation: "Single-Stranded Binding Proteins (SSBPs) bind to the separated single-stranded DNA after helicase unwinding, preventing the strands from reannealing (re-pairing) and keeping them available as templates for replication.",
    difficulty: "easy",
    lessonSource: "Gene Expression"
  },
  {
    topic: "gene_expression",
    questionText: "The beta clamp in DNA replication:",
    optionA: "Unwinds DNA",
    optionB: "Keeps DNA polymerase attached to the template strand",
    optionC: "Synthesizes RNA primers",
    optionD: "Removes RNA primers",
    correctAnswer: "B",
    explanation: "The beta clamp (also called the clamp or processivity factor) is a ring-shaped protein that encircles DNA and keeps DNA polymerase III attached to the template strand, ensuring processive synthesis without the polymerase falling off.",
    difficulty: "medium",
    lessonSource: "Gene Expression"
  },
  {
    topic: "gene_expression",
    questionText: "During RNA processing, introns are removed by:",
    optionA: "RNA polymerase",
    optionB: "Spliceosomes",
    optionC: "Ribosomes",
    optionD: "Helicase",
    correctAnswer: "B",
    explanation: "Introns (non-coding intervening sequences) are removed from pre-mRNA by spliceosomes — RNA/protein hybrid complexes. This splicing occurs in the nucleus before the mature mRNA is exported to the cytoplasm for translation.",
    difficulty: "medium",
    lessonSource: "Gene Expression"
  },
  {
    topic: "gene_expression",
    questionText: "The poly-A tail added to the 3' end of pre-mRNA:",
    optionA: "Is coded in the DNA gene sequence",
    optionB: "Consists of 100-200 adenine nucleotides added after transcription",
    optionC: "Is added to the 5' end",
    optionD: "Is removed during splicing",
    correctAnswer: "B",
    explanation: "The poly-A tail consists of 100-200 adenine nucleotides added to the 3' end of the primary transcript after cleavage at a specific site. These A's are NOT coded in the DNA gene. The tail protects mRNA from degradation and aids export from the nucleus.",
    difficulty: "medium",
    lessonSource: "Gene Expression"
  },
  {
    topic: "gene_expression",
    questionText: "Aminoacyl-tRNA synthetase is responsible for:",
    optionA: "Synthesizing mRNA",
    optionB: "Adding the correct amino acid to its corresponding tRNA",
    optionC: "Forming peptide bonds",
    optionD: "Unwinding DNA",
    correctAnswer: "B",
    explanation: "Aminoacyl-tRNA synthetase is a family of enzymes that charge tRNA molecules by attaching the correct amino acid to each tRNA according to its anticodon. This ensures fidelity in translation — the correct amino acid is delivered for each codon.",
    difficulty: "medium",
    lessonSource: "Gene Expression"
  },
  {
    topic: "gene_expression",
    questionText: "Rho factor is involved in:",
    optionA: "DNA replication initiation",
    optionB: "Transcription termination in prokaryotes",
    optionC: "Translation initiation",
    optionD: "RNA splicing",
    correctAnswer: "B",
    explanation: "The Rho factor is a protein involved in transcription termination in prokaryotes. It binds to the nascent RNA transcript and moves along it, causing RNA polymerase to dissociate from the DNA template when it reaches the terminator sequence.",
    difficulty: "hard",
    lessonSource: "Gene Expression"
  },
  // === GENETIC ENGINEERING (Lesson 2 Module 5) ~12 questions ===
  {
    topic: "genetic_engineering",
    questionText: "Genetic engineering is defined as:",
    optionA: "Natural selection of superior traits",
    optionB: "The transfer of DNA from one organism to another",
    optionC: "Random mutation of genes",
    optionD: "Traditional breeding of plants and animals",
    correctAnswer: "B",
    explanation: "Genetic engineering is the transfer of DNA from one organism to another. It allows plant breeders to move genes among unrelated species to produce plants with novel traits that could not be achieved through traditional breeding.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "Bt corn is genetically modified to:",
    optionA: "Grow faster",
    optionB: "Be resistant to the European corn borer by producing Cry proteins",
    optionC: "Have larger kernels",
    optionD: "Require less water",
    correctAnswer: "B",
    explanation: "Bt corn contains genes from Bacillus thuringiensis (Bt) that encode Cry (crystal delta-endotoxin) proteins toxic to the European corn borer and other insect pests. The Cry proteins bind to specific receptors on mid-gut cells of insects.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "The mechanism of Bt toxicity involves Cry proteins that:",
    optionA: "Digest the insect from the outside",
    optionB: "Bind to specific receptors on mid-gut epithelial cells, causing cell rupture",
    optionC: "Starve the insect",
    optionD: "Repel insects with odor",
    correctAnswer: "B",
    explanation: "Cry proteins bind to specific receptors on the membranes of insect mid-gut (epithelial) cells. This binding causes rupture of those cells, leading to insect death. If no specific receptor exists (as in humans), the Cry protein is not toxic.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "Agrobacterium tumefaciens is used in genetic engineering because:",
    optionA: "It kills plant pests",
    optionB: "Its Ti-plasmid can transfer DNA (t-DNA) into plant cells",
    optionC: "It fixes nitrogen",
    optionD: "It produces vitamins",
    correctAnswer: "B",
    explanation: "Agrobacterium tumefaciens naturally induces tumors on plants using its Ti-plasmid (Tumor-inducing plasmid). Scientists have harnessed this mechanism — the Ti-plasmid coordinates random insertion of t-DNA with genes of interest (like Cry) into plant genomes.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "Golden Rice was developed to:",
    optionA: "Increase yield",
    optionB: "Contain additional beta-carotene to combat vitamin A deficiency",
    optionC: "Resist drought",
    optionD: "Grow in saline soil",
    correctAnswer: "B",
    explanation: "Golden Rice was developed by PhilRice and IRRI to contain additional levels of beta-carotene, which the body converts into vitamin A. It was designed to help reduce childhood malnutrition and vitamin A deficiency, particularly in the Philippines.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "The 'terminator gene' technology refers to:",
    optionA: "Genes that kill pests",
    optionB: "Genetically engineered plants that produce sterile seeds",
    optionC: "Genes that prevent aging",
    optionD: "Technology that terminates viral infections",
    correctAnswer: "B",
    explanation: "The 'terminator gene' technology (officially 'technology protection system') refers to genetically engineered plants that produce sterile seeds. This was patented by Delta and Pine Land Co. and USDA, preventing farmers from saving seeds for the next planting season.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "Which US agency evaluates whether GMOs are safe to eat?",
    optionA: "USDA",
    optionB: "EPA",
    optionC: "FDA",
    optionD: "WHO",
    correctAnswer: "C",
    explanation: "The FDA (Food and Drug Administration) evaluates GMOs for food safety — determining if they are safe to eat. The USDA evaluates if they are safe to grow, and the EPA evaluates environmental safety (pesticides, novel microorganisms).",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "One major environmental concern about GMOs is:",
    optionA: "They grow too slowly",
    optionB: "Outcrossing (gene flow) from genetically-engineered crops to related wild species",
    optionC: "They require too much water",
    optionD: "They cannot survive in nature",
    correctAnswer: "B",
    explanation: "Outcrossing — the transfer of genes from genetically-engineered crops to related wild species through cross-pollination — is a major environmental concern. This could produce hybrids with weed-like characteristics that are difficult to control.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "Recombinant DNA (rDNA) technology involves:",
    optionA: "Random mutation of DNA",
    optionB: "Manipulating DNA isolated from one organism and introducing it into another",
    optionC: "Traditional cross-breeding",
    optionD: "Natural selection",
    correctAnswer: "B",
    explanation: "Recombinant DNA technology involves manipulating DNA isolated from animal, plant, or microbial cells and introducing it into another organism. Techniques include direct cellular uptake, forced introduction (gene gun), and using carrier organisms like Agrobacterium.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "The gene gun method of genetic engineering:",
    optionA: "Uses bacteria to transfer genes",
    optionB: "Fires DNA-coated metallic pellets into cells",
    optionC: "Uses viral vectors",
    optionD: "Inject DNA directly into the nucleus",
    correctAnswer: "B",
    explanation: "The gene gun (biolistics) fires a plastic bullet loaded with tiny metallic pellets coated with DNA. When a plate stops the bullet shell, the pellets continue toward cellular targets, penetrating cell walls and introducing foreign DNA into nuclei.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 5"
  },
  // Additional DNA Replication Questions
  {
    topic: "dna_replication",
    questionText: "Which of the following is NOT required for DNA replication?",
    optionA: "DNA template",
    optionB: "RNA primer",
    optionC: "Ribosomes",
    optionD: "DNA polymerase",
    correctAnswer: "C",
    explanation: "Ribosomes are required for translation (protein synthesis), not DNA replication. DNA replication requires: DNA template, RNA primers, DNA polymerase III, DNA polymerase I, helicase, DNA gyrase, ligase, and nucleotide triphosphates.",
    difficulty: "easy",
    lessonSource: "Gene Expression"
  },
  {
    topic: "dna_replication",
    questionText: "DNA polymerase III adds nucleotides in which direction?",
    optionA: "3' to 5'",
    optionB: "5' to 3'",
    optionC: "Both directions",
    optionD: "Randomly",
    correctAnswer: "B",
    explanation: "All DNA polymerases synthesize DNA in the 5' to 3' direction only. They add nucleotides to the free 3'-OH group of the growing chain. This is a fundamental property of DNA polymerases.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "Nucleotides are added during DNA replication as:",
    optionA: "Monophosphates",
    optionB: "Diphosphates",
    optionC: "Triphosphates (dNTPs) which also provide energy",
    optionD: "Free bases",
    correctAnswer: "C",
    explanation: "Nucleotides are added as deoxynucleoside triphosphates (dNTPs). The high-energy phosphate bonds in the triphosphate group provide the energy needed for the phosphodiester bond formation during polymerization.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "The initiation of DNA replication begins at specific sites called:",
    optionA: "Promoters",
    optionB: "Origins of replication",
    optionC: "Telomeres",
    optionD: "Centromeres",
    correctAnswer: "B",
    explanation: "DNA replication initiates at specific sites called origins of replication. Prokaryotes typically have a single origin, while eukaryotes have thousands of origins to ensure timely replication of their much larger genomes.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "Which non-essential amino acid promotes healthy brain function and is necessary for synthesis of DNA and RNA?",
    optionA: "Glycine",
    optionB: "Glutamine",
    optionC: "Proline",
    optionD: "Serine",
    correctAnswer: "B",
    explanation: "Glutamine promotes healthy brain function and is necessary for the synthesis of nucleic acids (DNA and RNA). It is a non-essential amino acid that the body can synthesize.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 1"
  },
  {
    topic: "dna_replication",
    questionText: "The clamp loader protein in DNA replication:",
    optionA: "Synthesizes DNA",
    optionB: "Loads the beta clamp onto DNA",
    optionC: "Removes RNA primers",
    optionD: "Unwinds the double helix",
    correctAnswer: "B",
    explanation: "The clamp loader (clamp holder) is responsible for loading the beta clamp onto the DNA template at the primer-template junction. This ATP-dependent process allows DNA polymerase III to achieve high processivity.",
    difficulty: "hard",
    lessonSource: "Gene Expression"
  },
  // Additional Transcription Questions
  {
    topic: "transcription",
    questionText: "Which of the following is NOT a difference between transcription and DNA replication?",
    optionA: "Transcription uses RNA polymerase; replication uses DNA polymerase",
    optionB: "Transcription uses only one DNA strand as template; replication uses both",
    optionC: "Transcription requires a primer; replication does not",
    optionD: "Transcription produces RNA; replication produces DNA",
    correctAnswer: "C",
    explanation: "Transcription does NOT require a primer — RNA polymerase can initiate synthesis de novo. DNA replication requires RNA primers. All other options correctly describe differences between transcription and replication.",
    difficulty: "medium",
    lessonSource: "Gene Expression"
  },
  {
    topic: "transcription",
    questionText: "In prokaryotes, transcription and translation can occur simultaneously because:",
    optionA: "They have a nuclear membrane",
    optionB: "They lack a nuclear membrane, so ribosomes can access mRNA while it is being transcribed",
    optionC: "They have larger ribosomes",
    optionD: "They use different genetic codes",
    correctAnswer: "B",
    explanation: "Prokaryotes lack a nuclear membrane, so transcription and translation are coupled — ribosomes can begin translating mRNA while it is still being transcribed. This is impossible in eukaryotes where transcription occurs in the nucleus and translation in the cytoplasm.",
    difficulty: "medium",
    lessonSource: "Gene Expression"
  },
  {
    topic: "transcription",
    questionText: "The promoter region in DNA is where:",
    optionA: "Transcription terminates",
    optionB: "RNA polymerase binds to initiate transcription",
    optionC: "Translation begins",
    optionD: "DNA replication starts",
    correctAnswer: "B",
    explanation: "The promoter is a specific DNA sequence upstream of a gene where RNA polymerase binds to initiate transcription. It contains consensus sequences (like the -10 and -35 boxes in prokaryotes) recognized by sigma factors.",
    difficulty: "easy",
    lessonSource: "Gene Expression"
  },
  {
    topic: "transcription",
    questionText: "RNA polymerase differs from DNA polymerase in that RNA polymerase:",
    optionA: "Requires a primer",
    optionB: "Can initiate synthesis without a primer",
    optionC: "Proofreads its work",
    optionD: "Works only in the 3' to 5' direction",
    correctAnswer: "B",
    explanation: "RNA polymerase can initiate RNA synthesis de novo without a primer, unlike DNA polymerase which requires an RNA primer with a free 3'-OH group. However, RNA polymerase has lower fidelity than DNA polymerase because it lacks proofreading exonuclease activity.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "Which codon serves as the start codon for translation?",
    optionA: "UAA",
    optionB: "UAG",
    optionC: "AUG",
    optionD: "UGA",
    correctAnswer: "C",
    explanation: "AUG is the start codon that initiates translation. It codes for methionine (formylated methionine in prokaryotes). The other options (UAA, UAG, UGA) are stop codons that terminate translation.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  {
    topic: "transcription",
    questionText: "Using the genetic code chart, the codon AUG codes for which amino acid?",
    optionA: "Lysine",
    optionB: "Methionine",
    optionC: "Tryptophan",
    optionD: "Phenylalanine",
    correctAnswer: "B",
    explanation: "AUG codes for Methionine (Met). To find this using the genetic code chart: locate A in the inner circle, U in the second circle, and G in the third circle — the corresponding amino acid in the outermost circle is Methionine.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 2"
  },
  // Additional Translation Questions
  {
    topic: "translation",
    questionText: "Translation occurs at which cellular structure?",
    optionA: "Nucleus",
    optionB: "Ribosome",
    optionC: "Golgi apparatus",
    optionD: "Mitochondria",
    correctAnswer: "B",
    explanation: "Translation (protein synthesis) occurs at ribosomes in the cytoplasm. Ribosomes read the mRNA sequence and assemble amino acids into a polypeptide chain according to the codon sequence.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "During translation initiation in prokaryotes, IF1 prevents:",
    optionA: "mRNA binding",
    optionB: "Premature binding of tRNA to the A-site",
    optionC: "Ribosome dissociation",
    optionD: "Peptide bond formation",
    correctAnswer: "B",
    explanation: "Initiation Factor 1 (IF1) binds to the A-site of the 30S subunit, preventing premature binding of tRNA to the A-site during initiation. This ensures that only the initiator fmet-tRNA can bind to the P-site first.",
    difficulty: "hard",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "The energy source for activating amino acids (attaching them to tRNA) is:",
    optionA: "GTP",
    optionB: "ATP",
    optionC: "NADH",
    optionD: "cAMP",
    correctAnswer: "B",
    explanation: "Amino acid activation (charging tRNA) requires energy from ATP. This reaction is catalyzed by aminoacyl-tRNA synthetase, which attaches the correct amino acid to its corresponding tRNA using ATP hydrolysis.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "After peptide bond formation during elongation, the ribosome:",
    optionA: "Dissociates immediately",
    optionB: "Translocates — moves along mRNA, shifting peptidyl-tRNA from A-site to P-site",
    optionC: "Releases the mRNA",
    optionD: "Adds another amino acid without moving",
    correctAnswer: "B",
    explanation: "After peptide bond formation, the ribosome translocates — it moves one codon along the mRNA. This shifts the peptidyl-tRNA from the A-site to the P-site and the empty tRNA exits, leaving the A-site free for the next incoming aminoacyl-tRNA.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  {
    topic: "translation",
    questionText: "A polypeptide chain can become a functional protein by:",
    optionA: "Immediate folding only",
    optionB: "Undergoing further processing including folding, cleavage, and post-translational modifications",
    optionC: "Directly from the ribosome without modification",
    optionD: "Translation only",
    correctAnswer: "B",
    explanation: "After translation, a polypeptide chain may undergo further processing to become a functional protein. This includes folding into its 3D structure, proteolytic cleavage, and post-translational modifications (phosphorylation, glycosylation, etc.).",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 4 Part 3"
  },
  // Additional Linkage Questions
  {
    topic: "linkage",
    questionText: "In genetic mapping, one map unit (centiMorgan) equals:",
    optionA: "1% recombination frequency",
    optionB: "10% recombination frequency",
    optionC: "50% recombination frequency",
    optionD: "100% recombination frequency",
    correctAnswer: "A",
    explanation: "One map unit (or centiMorgan, cM) equals 1% recombination frequency. It represents a 1% chance that two genes will be separated by crossing over during meiosis. Genes that are 1 cM apart have a 1% recombination frequency.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Genes on different chromosomes assort independently because of:",
    optionA: "Linkage",
    optionB: "Independent assortment during meiosis",
    optionC: "Crossing over",
    optionD: "Mutation",
    correctAnswer: "B",
    explanation: "Mendel's Law of Independent Segregation (Independent Assortment) states that genes on different chromosomes assort independently because homologous chromosome pairs align randomly at the metaphase plate during meiosis I.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Crossing over occurs during which stage of meiosis?",
    optionA: "Metaphase I",
    optionB: "Prophase I",
    optionC: "Anaphase I",
    optionD: "Telophase II",
    correctAnswer: "B",
    explanation: "Crossing over (genetic recombination) occurs during Prophase I of meiosis, when homologous chromosomes pair up (synapsis) and exchange segments. This creates new combinations of alleles on recombinant chromosomes.",
    difficulty: "easy",
    lessonSource: "Lesson 2 Module 3"
  },
  {
    topic: "linkage",
    questionText: "Sex-influenced traits differ from sex-limited traits in that they:",
    optionA: "Appear only in one sex",
    optionB: "May appear in both sexes but more frequently in one",
    optionC: "Are caused by genes on sex chromosomes only",
    optionD: "Are never genetic",
    correctAnswer: "B",
    explanation: "Sex-influenced (sex-controlled) traits may appear in both sexes but are expressed more frequently in one sex than the other. Examples: harelip, pattern baldness, and gout occur more frequently in men; spina bifida is more frequent in women.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
  // Additional Mutation Questions
  {
    topic: "mutation",
    questionText: "A missense mutation results in:",
    optionA: "A premature stop codon",
    optionB: "A different amino acid in the protein product",
    optionC: "No change in the amino acid sequence",
    optionD: "Deletion of an entire gene",
    correctAnswer: "B",
    explanation: "A missense mutation changes a codon to specify a different amino acid, resulting in an altered protein product. Example: sickle cell disease — glutamic acid is replaced by valine at position 6 of the beta-globin chain.",
    difficulty: "easy",
    lessonSource: "mutation-1"
  },
  {
    topic: "mutation",
    questionText: "Depurination is a spontaneous mutation caused by:",
    optionA: "Addition of a purine base",
    optionB: "Loss of a purine base (A or G) to form an apurinic site",
    optionC: "Replacement of a purine with a pyrimidine",
    optionD: "Duplication of a purine base",
    correctAnswer: "B",
    explanation: "Depurination is the spontaneous loss of a purine base (adenine or guanine) from DNA, leaving an apurinic (AP) site. If unrepaired, this can lead to mutations during replication when the DNA polymerase inserts an incorrect base opposite the gap.",
    difficulty: "hard",
    lessonSource: "mutation-1"
  },
  {
    topic: "mutation",
    questionText: "Deamination changes:",
    optionA: "A base to its normal complement",
    optionB: "A normal base to an atypical base (e.g., cytosine to uracil)",
    optionC: "The sugar-phosphate backbone",
    optionD: "The number of chromosomes",
    correctAnswer: "B",
    explanation: "Deamination is the removal of an amino group from a base, converting it to an atypical base. For example, cytosine can be deaminated to uracil, which would pair with adenine instead of guanine during replication, causing a C→T mutation.",
    difficulty: "hard",
    lessonSource: "mutation-1"
  },
  // Fix duplicate optionC above
  // Additional Genetic Engineering Questions
  {
    topic: "genetic_engineering",
    questionText: "Which of the following is a chemical mutagen?",
    optionA: "X-rays",
    optionB: "Colchicine",
    optionC: "Gamma rays",
    optionD: "Ultraviolet light",
    correctAnswer: "B",
    explanation: "Colchicine is a chemical mutagen that interferes with spindle formation during cell division, causing chromosome doubling. X-rays, gamma rays, and UV light are physical (radiation) mutagens, not chemical.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "A forward mutation is defined as a change from:",
    optionA: "Mutant to wild type",
    optionB: "Wild type (normal) to a new mutant genotype",
    optionC: "One mutant to another mutant",
    optionD: "Diploid to haploid",
    correctAnswer: "B",
    explanation: "A forward mutation is a change from the wild type (normal) genotype to a new mutant genotype. A reverse (back) mutation is a change from mutant back to wild type, restoring the original phenotype.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "The USDA evaluates GMOs for:",
    optionA: "Food safety for human consumption",
    optionB: "Safety to grow (plant pest risk)",
    optionC: "Environmental impact of pesticides",
    optionD: "International trade compliance",
    correctAnswer: "B",
    explanation: "The USDA (United States Department of Agriculture) evaluates GMOs for plant pest risk and whether they are safe to grow. The FDA evaluates food safety, and the EPA evaluates environmental safety of pesticides and novel microorganisms.",
    difficulty: "medium",
    lessonSource: "Lesson 2 Module 5"
  },
  {
    topic: "genetic_engineering",
    questionText: "An auxotrophic mutant in bacteria:",
    optionA: "Can synthesize all required nutrients",
    optionB: "Lacks a gene product for an essential metabolic pathway and needs the metabolite supplied in media",
    optionC: "Is resistant to antibiotics",
    optionD: "Can survive under all conditions",
    correctAnswer: "B",
    explanation: "An auxotrophic mutant lacks a functional gene for an enzyme in a biosynthetic pathway and cannot synthesize a required metabolite (like an amino acid). It can only survive if the metabolite is supplied as a nutrient in the culture medium.",
    difficulty: "hard",
    lessonSource: "mutation-1"
  },
  {
    topic: "genetic_engineering",
    questionText: "A conditional-lethal mutant in bacteria:",
    optionA: "Dies under all conditions",
    optionB: "Can survive only under specific conditions (e.g., temperature-sensitive mutants)",
    optionC: "Is resistant to antibiotics",
    optionD: "Cannot be cultured",
    correctAnswer: "B",
    explanation: "A conditional-lethal mutant can survive under permissive conditions but dies under restrictive conditions. For example, temperature-sensitive mutants survive below 30°C but die at higher temperatures because the mutation affects an amino acid essential for protein tertiary structure.",
    difficulty: "hard",
    lessonSource: "mutation-1"
  },
  {
    topic: "genetic_engineering",
    questionText: "Temperature-sensitive lethal genes in organisms are examples of:",
    optionA: "Unconditional lethals",
    optionB: "Conditional lethals (monophasic or polyphasic)",
    optionC: "Semi-lethals only",
    optionD: "Dominant lethals only",
    correctAnswer: "B",
    explanation: "Temperature-sensitive lethal genes are conditional lethals — lethality occurs only when the organism is exposed to a restrictive temperature. Monophasic lethality occurs during one specific developmental stage; polyphasic lethality occurs during two or more stages.",
    difficulty: "hard",
    lessonSource: "Lesson 1 Module 3"
  },
  // Additional Gene Expression
  {
    topic: "gene_expression",
    questionText: "The diameter of a DNA molecule is approximately:",
    optionA: "10 angstroms",
    optionB: "20 angstroms",
    optionC: "34 angstroms",
    optionD: "100 angstroms",
    correctAnswer: "B",
    explanation: "The diameter of the DNA double helix is approximately 20 angstroms (2 nanometers). The helix completes one turn every 34 angstroms, and each base pair occupies about 3.4 angstroms along the axis.",
    difficulty: "hard",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "The major groove in DNA is important because:",
    optionA: "It stores energy",
    optionB: "It allows proteins to access base sequences for recognition and binding",
    optionC: "It contains the phosphate groups",
    optionD: "It prevents DNA unwinding",
    correctAnswer: "B",
    explanation: "The major groove of DNA is wide enough for proteins (like transcription factors and DNA-binding proteins) to read the base sequence and bind specifically. The edges of the base pairs expose functional groups that allow sequence-specific recognition.",
    difficulty: "hard",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "The sugar in DNA is called:",
    optionA: "Ribose",
    optionB: "Deoxyribose",
    optionC: "Glucose",
    optionD: "Fructose",
    correctAnswer: "B",
    explanation: "DNA contains deoxyribose sugar, which lacks an oxygen atom at the 2' position compared to ribose (found in RNA). This makes DNA more chemically stable than RNA, which is important for long-term storage of genetic information.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 4 Part 1"
  },
  {
    topic: "gene_expression",
    questionText: "Internal factors affecting gene expression include:",
    optionA: "Temperature only",
    optionB: "Age and sex of the organism",
    optionC: "Light exposure",
    optionD: "Nutrition only",
    correctAnswer: "B",
    explanation: "Internal factors affecting gene expression include age (different genetic traits appear at different ages — e.g., pattern baldness at 20-30 years, diabetes mellitus at 40-60 years) and sex (sex-limited and sex-influenced traits). Temperature, light, and nutrition are external factors.",
    difficulty: "easy",
    lessonSource: "Lesson 1 Module 3"
  },
  {
    topic: "dominance",
    questionText: "The onset of infantile amaurotic idiocy usually occurs at:",
    optionA: "Birth",
    optionB: "4-6 months after birth",
    optionC: "10 years of age",
    optionD: "20-30 years of age",
    correctAnswer: "B",
    explanation: "Infantile amaurotic idiocy (Tay-Sachs disease) typically appears 4-6 months after birth. Other age-related genetic trait onsets: periodic paralysis starts at 10 years, pattern baldness at 20-30 years, and diabetes mellitus at 40-60 years.",
    difficulty: "medium",
    lessonSource: "Lesson 1 Module 3"
  },
];

